// <auto-generated />
using System;
using BackEndSearchFakebook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEndSearchFakebook.Migrations
{
    [DbContext(typeof(FakebookMinhContext))]
    [Migration("20260701032039_RemoveOwnerId")]
    partial class RemoveOwnerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndSearchFakebook.Models.Object", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int?>("SortKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("objects_pkey");

                    b.ToTable("objects", (string)null);
                });

            modelBuilder.Entity("BackEndSearchFakebook.Models.Token", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("TokenText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_text");

                    b.HasKey("Id")
                        .HasName("tokens_pkey");

                    b.HasIndex(new[] { "TokenText" }, "tokens_token_text_key")
                        .IsUnique();

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("TokenObject", b =>
                {
                    b.Property<long>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.HasKey("TokenId", "ObjectId")
                        .HasName("token_object_pkey");

                    b.HasIndex(new[] { "ObjectId" }, "idx_token_object_obj_id");

                    b.ToTable("token_object", (string)null);
                });

            modelBuilder.Entity("TokenObject", b =>
                {
                    b.HasOne("BackEndSearchFakebook.Models.Object", null)
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("token_object_object_id_fkey");

                    b.HasOne("BackEndSearchFakebook.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("token_object_token_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
